server:
  port: 8004
  
 
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.12.102
    port: 5672
    username: admin
    password: admin
sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"
    